# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo ${{ secrets.FOO }}
    - run: npm install
    - run: npm run build --if-present
      env:
        W3C_API_KEY: ${{ secrets.W3C_API_KEY }}
        SKIP_NETWORK: true 
    - name: Notify failure
      uses: rectalogic/notify-irc@v1
      if: ${{ failure() }}
      with:
        server: "irc.w3.org"
        port: 6679
        channel: "#pubrules"
        nickname: gh-action-notifier
        tls: true
        message: |
          ${{ github.actor }} pushed to {{ github.repository }}. ${{ github.event.pull_request }} FAILED
    - name: Notify success
      uses: rectalogic/notify-irc@v1
      if: ${{ success() }}
      with:
        server: "irc.w3.org"
        port: 6679
        channel: "#pubrules"
        nickname: gh-action-notifier
        tls: true
        message: |
          ${{ github.actor }} pushed to {{ github.repository }}. ${{ github.event.pull_request }} FAILED

